# Generated by Django 5.1.4 on 2024-12-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PluginModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plugin",
                    models.CharField(
                        choices=[("PluginA", "Plugin A"), ("PluginB", "Plugin B")],
                        max_length=50,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
